#!/bin/bash
while read -r line; do
    echo $line
    REPO_CATEGORY=`echo $line | awk -F "/|:" '{print $2}'`
    REPO_NAME=`echo $line | awk -F "/|:" '{print $3}'`
    REPO_TAG=`echo $line | awk -F "/|:" '{print $4}'`
    REPO_SOURCE=`echo gcr.io/$REPO_CATEGORY/$REPO_NAME:$REPO_TAG`
    REPO_TARGET=`echo pythias/$REPO_CATEGORY.$REPO_NAME:$REPO_TAG`
    docker images
    docker pull $REPO_SOURCE
    docker tag $REPO_TARGET $REPO_SOURCE
    docker push $REPO_TARGET
done < repo
